FROM nginx:1.25-alpine
COPY index.html /usr/share/nginx/html/index.html
COPY main.js /usr/share/nginx/html/main.js
COPY default.conf /etc/nginx/conf.d/default.conf
# porta 80 exposta por padrão pela imagem
    